###### ocs v ######
ocs:
  image: quay.io/njuaplusplus/ocs
  privileged: true
  restart: always
  environment:
    - CA_CN=OCS CA
    - CA_ORG=OCS ORG
    - SERVER_CN=www.example.com
    - SERVER_ORG=server org
    - USER_CN=user
    - USER_UNIT=user unit
    - P12_NAME=userp12
    - P12_PASS=123456
    - ROUTE_ALL=false
  volumes:
    - /root/docker-ocserv/ocserv/:/etc/ocserv/
    - /root/docker-ocserv/certs/:/opt/certs/
  ports:
    - "10443:443"
    - "10443:443/udp"
###### End of  ocs v ######
